package btcman

const (
	DEFAULT_CONSOLIDATION_INTERVAL        = 60
	DEFAULT_CONSOLIDATION_TRANSACTION_FEE = 1000
	DEFAULT_UTXO_THRESHOLD                = 5000
	DEFAULT_MIN_UTXO_CONSOLIDATION_AMOUNT = 10
)
